{% set name = "hpc05" %}
{% set version = "2.0.6" %}
{% set sha256 = "caef40ed18042fafa5e37b61727a65d91d111ef077390a45c2d9288e3e47bca9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.zip
  url: https://github.com/basnijholt/hpc05/archive/v{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 3
  skip: true  # [py<36 or win]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - paramiko
    - ipyparallel
    - tornado
    - pexpect
    - psutil
    - dill

test:
  imports:
    - hpc05
    - hpc05_culler
    - hpc05_monitor

about:
  home: https://hpc05.readthedocs.io/
  license: MIT
  license_file: LICENSE
  summary: ipyparallel Client and convenience package for a PBS or SLURM cluster with a headnode.
  dev_url: https://github.com/basnijholt/hpc05

extra:
  recipe-maintainers:
    - basnijholt
