{% set name = "hpc05" %}
{% set version = "2.0.2" %}
{% set sha256 = "30ca3aa6e76eabbf4bde34e2f79542ddb4cdeacfcb3db811f254d7294d1a9a42" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.zip
  url: https://github.com/basnijholt/hpc05/archive/v{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<36 or win]
  script:
   - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - paramiko
    - ipyparallel
    - tornado
    - pexpect
    - psutil
    - dill

test:
  imports:
    - hpc05
    - hpc05_culler
    - hpc05_monitor

about:
  home: http://github.com/basnijholt/hpc05
  license: MIT
  license_file: LICENSE
  summary: "ipyparallel Client and convenience package for a PBS or SLURM cluster with a headnode."
  dev_url: https://github.com/basnijholt/hpc05

extra:
  recipe-maintainers:
    - basnijholt
