appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZbKMZFu0I1bV2fCpSXGZer/FAHwOqyEpMlBsuaKL2JhKZM0AcKlZqXLfTI7Rnz1dmgxU5TNg8norfJsRn3j3CrFFO7dDGyImkBeWua3A57z96kHKa046qzOMlgGSzqQY2YQnVSWKMRb03yepptoCcbLfXFenAqzgCiI6WSAw/G3/OXwL6jDFCZcwodbJuzBy0/JntLqBDcSyWSWARMrwyO8ExwLYUpfmAbxo7Ae4CWJuwZN0id7M+fu3c7dHJOxb80kFtjK1Rpej/8DW0OKrf9WS0f2gbDr014gjybmNxee9d672mkjOdGLGFG+sv/8BiTlUjQA5cwFm9HZhbOXuCaiKkjtpuNEiBosTophmTwpE+w2fgKUmQU2iaSeha1PM4Ro4xXTnDtpTJnKqOdX7WnVI4Nj7jn4971/7qAFOXY3KXrjFyHxrZQOScNwErr7aVS1EjB/SDDlmVEMwQncaag4no0CY7nowx9gfcVCMMi2TQCtQyAreKMsP1evnexFw43GHaNtezrxt5+Q8esRaA8/h4TzLelsi40rKDlw9Z1AawJCWU+vzTZ1ZxiT9CfTYWwswF7/1g1UKZJLOnNHm8dvt17u3UDV6uHwerBdbibK1diEMWOem3ouHFBnjRuYjxlhjUKDXPoUgXcSKM6g6Uao6fnc7/fSqd50htvU/r3I=}
conda_forge_output_validation: true
